# -*- coding: utf-8 -*-
"""Dsa.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H1nw9spMA9o0-9v_Xo-FPCNVEt-CNwSE

Data Structure => it is the basic concept of every programming language also it is the way to store and organize the data so it can be easily accesiable

why we use Data Structure => there are diffrent diffrent type of data structure and also the organization of data is the most important part but also as programmer you have to write the code with more effective way like how fast you can access the data and many more there we use the data structure according to our need.

there are two type of data structure in python 
1) inbuilt data structure
2) user defined data structure

list, dict, set, tuple are in built data structure in python

user defined data structure are stack ,queue, linkedlist , tree, graph

List and Tuple

1   List is Mutable and Tuple is Immutable.
2   List is support Indexing and Tuple also support Indexing
3   List is slow and Tuple is faster than list
4   List and Tuple Both can be nested
5   List is enclosed with subscript [] while for tuple we use Paranthesis ().
6   List and Tuple both are ordered.
7   List and Tuple both support the duplicate values.
"""

# How to create a list in python
list1 = []
print(list1)

# You can also use the list constructor for creating the list
list2 = list()
print(list2)

# List support Positive and negative indexing
List1 = [4,"qwerty",8.0,7,91,67,89]
print(List1[0:8:3]) # (start,end,step)

# You can add an element in list by using append method
List1.append(45)
print(List1)

# You can remove an element by using remove method
List1.remove(67)
print(List1)

# How create a tuple in python
tuple1 = ()
print(tuple1)

# Tuple Constructor
tuple1 = tuple()
print(tuple1)

# tuple support Duplicates
tuple1 = (4, 'qwerty', 8.0, 7,7, 91, 89, 45)
print(tuple1)

# length of tuple
tuple1 = (4, 'qwerty', 8.0, 7,7, 91, 89, 45)
print(len(tuple1))

# tuple also support Indexing
tuple1 = (4, 'qwerty', 8.0, 7,7, 91, 89, 45)
tuple1[4]

# Negative indexing in tuple
tuple1 = (4, 'qwerty', 8.0, 7,7, 91, 89, 45)
tuple1[-5:]



